### ISSUE TITLE
team page allignment.

### ISSUE THREAD

**Issue by Amankumar29** [Catalyst-CSE/OpenSourceEvents-Frontend#104]
having different rows 
1.admins
2.mentors
3.members
4.contributors
and make them in center.

**Comment by Amankumar29** [comment]
@anubhavsingh16

**Comment by ShauryaBhandari** [comment]
Hey, I came across this via gssoc. Can I work on this?

**Comment by anubhavsingh16** [comment]
Yes @ShauryaBhandari

**Comment by ShauryaBhandari** [comment]
origin	https://github.com/Catalyst-CSE/OpenSourceEvents-Frontend.git (fetch)
origin	https://github.com/Catalyst-CSE/OpenSourceEvents-Frontend.git (push)
upstream	https://github.com/Catalyst-CSE/OpenSourceEvents-Frontend.git (fetch)
upstream	https://github.com/Catalyst-CSE/OpenSourceEvents-Frontend.git (push)
After doing git remote -v inside the repo, this is coming rather than showing my own username, could you please help?

**Comment by ShauryaBhandari** [comment]
Hi @anubhavsingh16 , please unassign the issue that was assigned to me above, the codebase is really very messy to work with. I tried to clear out the issue but it is really very messy. There is no proper indentation and the divs have been wrongly placed. 
A 15-minute task took an hour to just clean up the code, but I decided to not waste my time any further.
